services:
  web-server:
    build: ./web-server
    image: web-server:latest
    container_name: web-server
    hostname: web-server
    volumes:
      - ./web-server:/opt/web-server
    ports:
      - 3000:3000

  api-server:
    build: ./api-server
    image: api-server:latest
    container_name: api-server
    hostname: api-server
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/postgres
    volumes:
      - ./api-server:/opt/api-server
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15.7-alpine3.20
    container_name: database
    hostname: database
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1s
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 5432:5432
